package supportinventory

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func repositoryConfig(t *testing.T) (Config, string) {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	return Config{
		Rules: filepath.Join(root, "internal/cncfcheck/data/rules.json"), Landscape: filepath.Join(root, "internal/cncfcheck/data/landscape-projects.json"),
		CertContract: filepath.Join(root, "internal/certmanagervalues/source-contract-v1.json"), PrometheusContract: filepath.Join(root, "internal/prometheusmode/source-contract-v1.json"),
		SPIFFEProfile: filepath.Join(root, "internal/spiffex509svid/data/profile.json"), CloudEventsProfile: filepath.Join(root, "internal/cloudeventsstructuredjson/data/profile.json"),
		TiKVProfile: filepath.Join(root, "internal/tikvgcpv2/data/profile.json"), CNCFPrepareSource: filepath.Join(root, "internal/communityapp/cncf_prepare.go"),
		SelectedSourceManifest: filepath.Join(root, "docs/data/selected-source-records-v1.json"),
	}, root
}

func TestSupportInventory_Generate_MatchesAcceptedInventory(t *testing.T) {
	cfg, root := repositoryConfig(t)
	jsonOutput, markdownOutput, err := Generate(cfg)
	if err != nil {
		t.Fatal(err)
	}
	wantJSON, err := os.ReadFile(filepath.Join(root, "docs/generated/community-support-inventory.json"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(jsonOutput, wantJSON) {
		t.Fatalf("generated JSON differs: got %d bytes want %d", len(jsonOutput), len(wantJSON))
	}
	wantMarkdown, err := os.ReadFile(filepath.Join(root, "docs/generated/community-support-inventory.md"))
	if err != nil {
		t.Fatal(err)
	}
	want := strings.Replace(string(wantMarkdown), "Generated by `scripts/generate_support_inventory.py`; do not edit by hand.", "Generated by `cmd/prufyx-maintainer`; do not edit by hand.", 1)
	if markdownOutput != want {
		t.Fatalf("generated Markdown differs: got %d bytes want %d", len(markdownOutput), len(want))
	}
}

func TestSupportInventory_DecodeStrict_RejectsDuplicateFields(t *testing.T) {
	if _, err := decodeStrict([]byte(`{"schema":"one","schema":"two"}`)); err == nil {
		t.Fatal("expected duplicate field rejection")
	}
}

func TestSupportInventory_PreparerProjects_ReadsCallableDispatchOnly(t *testing.T) {
	path := filepath.Join(t.TempDir(), "cncf_prepare.go")
	raw := "package communityapp\nfunc prepare(project *string, raw []byte) {\n\tswitch *project {\n\tcase \"validation-only\":\n\t}\n\tvar prepared cncfprepare.Prepared\n\tswitch *project {\n\tcase \"callable\", \"grouped\":\n\t\tprepared, err = cncfprepare.PrepareCallable(raw)\n\t}\n}\n"
	if err := os.WriteFile(path, []byte(raw), 0o600); err != nil {
		t.Fatal(err)
	}
	projects, err := preparerProjects(path)
	if err != nil {
		t.Fatal(err)
	}
	if len(projects) != 2 || !projects["callable"] || !projects["grouped"] {
		t.Fatalf("unexpected projects: %#v", projects)
	}
}

func TestSupportInventory_ConformanceProfile_RejectsMalformedRuleWithoutPanic(t *testing.T) {
	profile := map[string]any{"rules": []any{"not-an-object"}}
	if err := requireSingleRule(profile, "expected"); err == nil {
		t.Fatal("expected malformed rule rejection")
	}
}
